### ISSUE TITLE
[Feature]: block index for OpenEphysBinaryRecordingInterface

### ISSUE THREAD

**Issue by johnmbarrett** [catalystneuro/neuroconv#692]
### What would you like to see added to NeuroConv?

Please add support for loading multi-block Open Ephys datasets, either one block at a time or all at once.

Right now OpenEphysBinaryRecordingInterface throws an error if you try to load a multi-block Open Ephys dataset (i.e. one with more than one experiment folder under the top-level folder). Right now as far as I can tell the only workaround would be to split out each experiment into separate folders, but that's fiddly for users with lots of multi-block recordings. With a two-line change to pass the block_index through to the underlying SpikeInterface extractor it seems to load just fine. Not sure how feasible or necessary it would be to load all blocks with a single OpenEphysBinaryRecordingInterface instance, I think the single-block solution is fine for my purposes.

### Is your feature request related to a problem?

I have a multi-experiment OpenEphys recording and I want to load it with OpenEphysBinaryRecordingInterface.

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
Can you show the code for loading this in spikeinterface? Do you have some data that would you be willing to share with us that we could use as test?

**Comment by CodyCBakerPhD** [comment]
Can someone from SI also clarify what 'multi-block' means? Is that multi-segment (different time spans of same recording, already handled by NeuroConv) or recognized as a different stream (and therefore, here in NeuroConv, you'd have a separate interface per stream, so user is requesting a convenient `OpenEphysConverter` for bundling all streams)

**Comment by johnmbarrett** [comment]
Apologies for the lack of clarity. Open Ephys recordings have three levels of time organisation: sessions (I think each time you open the GUI), experiments (each time you hit the play button in Open Ephys GUI - referred to as 'blocks' in SpikeInterface) and recording (each time you hit the record button), that are organised hierarchically in the Open Ephys binary format folder structure. I'll go record a brief set of example data for testing purposes.

To load a specific experiment/block in SpikeInterface, specify the block_index, like so:

`spikeinterface.extractors.read_openephys(folder,block_index=block_index,stream_id=stream_id)`

**Comment by CodyCBakerPhD** [comment]
We can certainly expose the block argument easily then

It looks like GIN might have some example data already for this

@johnmbarrett can you confirm if this folder looks similar to what you would expect? https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/openephysbinary/v0.6.x_neuropixels_multiexp_multistream/Record%20Node%20101

Are the 'blocks' equal to `["experiment1", "experiment3", "experiment6"]` in that case?

**Comment by h-mayorquin** [comment]
Ah, thanks @CodyCBakerPhD . I was going to say that! 

 but I strongly welcome having some new test data that @johnmbarrett will provide for us : D

Concerning block, comes all the way from neo:
https://neo.readthedocs.io/en/latest/read_and_analyze.html#dataset-structure

**Comment by johnmbarrett** [comment]
Okay, in the time it's taken to not even finish zipping the data I was trying to work with, it turned out to be quicker to boot up my recording PC, hook up a Neuropixels probe, run a very quick test recording, and [upload it to Google drive](https://drive.google.com/file/d/1F8ThEgE0LYJ33sXID_WY8gpLbdrfOeqj/view?usp=sharing).

It's a broken probe and nothing is connecting to the Intan DAQ, so it should like about 3 seconds of noise split across 2 blocks and 3 segments, but should suffice for testing purposes. Will be back with the real data when it's ready.

For clarity, one stream and one block at a time is perfectly sufficient for my purposes.

**Comment by CodyCBakerPhD** [comment]
@johnmbarrett This ought to be working now if you want to give it a try

```
pip install git+https://github.com/catalystneuro/neuroconv.git@add_openephys_block_index
```

**Comment by johnmbarrett** [comment]
Looks great and seems to work with my test data, thanks for your quick attention to this! Looking forward to playing with this library! I still have that large dataset if you want it for testing/development purposes, just let me know and I'll upload it
